version: '3.0'

expectations:
  population_size: 10000

actions:

  extract_fixed:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_fixed.py
      --output output/extracts/extract_fixed.arrow
      --dummy-data-file lib/dummydata/dummyinput_fixed.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_fixed.arrow

  extract_varying:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_varying.py
      --output output/extracts/extract_varying.arrow
      #--dummy-data-file lib/dummydata/dummyinput_varying.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_varying.arrow

  process:
    run: r:v2 analysis/process.R
    needs: [extract_fixed, extract_varying]
    outputs:
      highly_sensitive:
        rds: output/process/*.rds
      moderately_sensitive:
        csv: output/process/*.csv
        txt: output/process/*.txt

# report vaccine history over entire observational period ---
  report_history:
    run: r:v2 analysis/report_history.R
    needs: [process]
    outputs:
      moderately_sensitive:
        csv: output/report_history/*.csv
        png: output/report_history/*.png

 # report detailed vaccine history at specific snapshots in time ----

 # 2020-12-08
  extract_snapshot_20201208:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20201208.arrow
      -- 20201208
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20201208.arrow

  report_snapshot_20201208:
    run: r:v2 analysis/report_snapshot.R 20201208
    needs: [extract_snapshot_20201208, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20201208/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20201208/*.csv
        png: output/report_snapshot_20201208/*.png
        txt: output/report_snapshot_20201208/*.txt

 # 2021-09-06
  extract_snapshot_20210906:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20210906.arrow
      -- 20210906
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20210906.arrow

  report_snapshot_20210906:
    run: r:v2 analysis/report_snapshot.R 20210906
    needs: [extract_snapshot_20210906, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20210906/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20210906/*.csv
        png: output/report_snapshot_20210906/*.png
        txt: output/report_snapshot_20210906/*.txt

  coverage_20210906_sex:
    run: kaplan-meier-function:v0.0.17
      --df_input=output/report_snapshot_20210906/*.arrow
      --dir_output=output/report_snapshot_20210906/coverage/
      --subgroups=sex
      --origin_date=snapshot_date
      --event_date=vax_date
      --censor_date=censor_date
      --min_count=10
      --method=constant
      --plot=TRUE
      --contrast=FALSE
      --filename_suffix=sex
    needs: [report_snapshot_20210906]
    outputs:
      moderately_sensitive:
        png: output/report_snapshot_20210906/coverage/*.png
        csv: output/report_snapshot_20210906/coverage/*.csv

 # 2022-04-01
  extract_snapshot_20220401:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20220401.arrow
      -- 20220401
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20220401.arrow

  report_snapshot_20220401:
    run: r:v2 analysis/report_snapshot.R 20220401
    needs: [extract_snapshot_20220401, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20220401/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20220401/*.csv
        png: output/report_snapshot_20220401/*.png
        txt: output/report_snapshot_20220401/*.txt

 # 2022-09-12
  extract_snapshot_20220912:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20220912.arrow
      -- 20220912
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20220912.arrow

  report_snapshot_20220912:
    run: r:v2 analysis/report_snapshot.R 20220912
    needs: [extract_snapshot_20220912, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20220912/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20220912/*.csv
        png: output/report_snapshot_20220912/*.png
        txt: output/report_snapshot_20220912/*.txt

 # 2023-04-03
  extract_snapshot_20230403:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20230403.arrow
      -- 20230403
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20230403.arrow

  report_snapshot_20230403:
    run: r:v2 analysis/report_snapshot.R 20230403
    needs: [extract_snapshot_20230403, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20230403/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20230403/*.csv
        png: output/report_snapshot_20230403/*.png
        txt: output/report_snapshot_20230403/*.txt

 # 2023-09-11
  extract_snapshot_20230911:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20230911.arrow
      -- 20230911
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20230911.arrow

  report_snapshot_20230911:
    run: r:v2 analysis/report_snapshot.R 20230911
    needs: [extract_snapshot_20230911, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20230911/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20230911/*.csv
        png: output/report_snapshot_20230911/*.png
        txt: output/report_snapshot_20230911/*.txt

 # 2024-04-01
  extract_snapshot_20240401:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20240401.arrow
      -- 20240401
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20240401.arrow

  report_snapshot_20240401:
    run: r:v2 analysis/report_snapshot.R 20240401
    needs: [extract_snapshot_20240401, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20240401/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20240401/*.csv
        png: output/report_snapshot_20240401/*.png
        txt: output/report_snapshot_20240401/*.txt

 # 2024-10-03
  extract_snapshot_20241003:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20241003.arrow
      -- 20241003
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20241003.arrow

  report_snapshot_20241003:
    run: r:v2 analysis/report_snapshot.R 20241003
    needs: [extract_snapshot_20241003, process]
    outputs:
      highly_sensitive:
        arrow: output/report_snapshot_20241003/*.arrow
      moderately_sensitive:
        csv: output/report_snapshot_20241003/*.csv
        png: output/report_snapshot_20241003/*.png
        txt: output/report_snapshot_20241003/*.txt
