version: '3.0'

expectations:
  population_size: 10000

actions:

  extract_fixed:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_fixed.py
      --output output/extracts/extract_fixed.arrow
      --dummy-data-file lib/dummydata/dummyinput_fixed.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_fixed.arrow

  extract_varying:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_varying.py
      --output output/extracts/extract_varying.arrow
      --dummy-data-file lib/dummydata/dummyinput_varying.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_varying.arrow

