version: '3.0'

expectations:
  population_size: 10000

actions:

  extract_fixed:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_fixed.py
      --output output/extracts/extract_fixed.arrow
      --dummy-data-file lib/dummydata/dummyinput_fixed.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_fixed.arrow

  extract_varying:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_varying.py
      --output output/extracts/extract_varying.arrow
      --dummy-data-file lib/dummydata/dummyinput_varying.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_varying.arrow



  process:
    run: r:latest analysis/process.R
    needs: [extract_fixed, extract_varying]
    outputs:
      highly_sensitive:
        rds: output/process/*.rds

# report vaccine history over entire observational period ----

  report_history:
    run: r:latest analysis/report_history.R
    needs: [process]
    outputs:
      moderately_sensitive:
        csv: output/report_history/*.csv
        png: output/report_history/*.png

 # report detailed vaccine history at specific snapshots in time ----

  extract_snapshot_20230930:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_snapshot.py
      --output output/extracts/extract_snapshot_20230930.arrow
      -- 2023-09-30
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_snapshot_20230930.arrow

  report_snapshot_20230930:
    run: r:latest analysis/report_snapshot.R 2023-09-30
    needs: [extract_snapshot_20230930, process]
    outputs:
      moderately_sensitive:
        #csv: output/report_snapshot_20230930/*.csv
        png: output/report_snapshot_20230930/*.png
